# Snowflake account details
SNOWFLAKE_ACCOUNT = "mtpehjr-da80212"
# Snowflake user credentials
SNOWFLAKE_USER = "PYTHON_USER"
SNOWFLAKE_PASSWORD = "Py_123456"
SNOWFLAKE_ROLE = "PUBLIC"
SNOWFLAKE_DATABASE = "TEST_DB"
SNOWFLAKE_SCHEMA = "PUBLIC"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
